### ISSUE TITLE
  Error: Unable to locate executable file: direnv. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [aldoborrero/use-nix-action#5]
Error: Unable to locate executable file: direnv.
Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

https://github.com/I-Want-ToBelieve/yakite/actions/runs/6975916441/job/18983682132

```yaml
name: Version

on:
  push:
    branches:
      - release/**

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v14
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Verify Nix Installation
        run: nix shell nixpkgs#nix-info -c nix-info -m

      - name: Install direnv with Nix
        uses: aldoborrero/direnv-nix-action@v2
        with:
          use_nix_profile: true
          nix_channel: nixpkgs

      - name: Load PATH Changes
        run: direnv exec . sh -c 'echo $PATH' > "$GITHUB_PATH"
      - name: Load other environment changes
        run: direnv export gha >> "$GITHUB_ENV"

      - name: Install Dependencies
        run: pnpm install

      - name: Setup Git User
        run: git-user:setup

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm run version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


```
